// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVkRYkAj7DGT1M0Tv6NFHxZZ5DRQ1VAHI',
    appId: '1:371067537879:web:60ba71336bc9cef77d6392',
    messagingSenderId: '371067537879',
    projectId: 'careercenter-cc625',
    authDomain: 'careercenter-cc625.firebaseapp.com',
    storageBucket: 'careercenter-cc625.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwkGS0CRP4fc1BmQT2zT2BmXQBoLGCT38',
    appId: '1:371067537879:android:f55910b38bf322fb7d6392',
    messagingSenderId: '371067537879',
    projectId: 'careercenter-cc625',
    storageBucket: 'careercenter-cc625.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS3cxk4Wv9VF8G6strqp-FtvqWEhchjKU',
    appId: '1:371067537879:ios:264f3b6862b73d397d6392',
    messagingSenderId: '371067537879',
    projectId: 'careercenter-cc625',
    storageBucket: 'careercenter-cc625.appspot.com',
    iosBundleId: 'com.example.flutterProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS3cxk4Wv9VF8G6strqp-FtvqWEhchjKU',
    appId: '1:371067537879:ios:264f3b6862b73d397d6392',
    messagingSenderId: '371067537879',
    projectId: 'careercenter-cc625',
    storageBucket: 'careercenter-cc625.appspot.com',
    iosBundleId: 'com.example.flutterProje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVkRYkAj7DGT1M0Tv6NFHxZZ5DRQ1VAHI',
    appId: '1:371067537879:web:d0fa57cbfec1457d7d6392',
    messagingSenderId: '371067537879',
    projectId: 'careercenter-cc625',
    authDomain: 'careercenter-cc625.firebaseapp.com',
    storageBucket: 'careercenter-cc625.appspot.com',
  );
}
